# Generated by Django 3.2.25 on 2025-12-17 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields
import quiz.models.question


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('team_code', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=255)),
                ('team_lead_name', models.CharField(max_length=255)),
                ('team_lead_email', models.EmailField(max_length=254)),
                ('college_name', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'events_participant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('guidelines', models.TextField(blank=True)),
                ('time_limit_minutes', models.PositiveIntegerField(help_text='Time limit in minutes')),
                ('max_attempts', models.PositiveIntegerField(default=1, help_text='Maximum attempts allowed per team')),
                ('warnings_allowed', models.PositiveIntegerField(default=2, help_text='Number of warnings before auto exit')),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('shuffle_options', models.BooleanField(default=True)),
                ('allow_immediate_results', models.BooleanField(default=False, help_text='Allow users to see results immediately after submission')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quiz_quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option_ids', djongo.models.fields.JSONField(default=list)),
                ('is_marked_for_review', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'quiz_answers',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('quiz_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('team_code', models.CharField(max_length=50)),
                ('team_lead_email', models.EmailField(max_length=254)),
                ('roll_number', models.CharField(blank=True, max_length=100)),
                ('college_name', models.CharField(blank=True, max_length=255)),
                ('extra_member_name', models.CharField(blank=True, max_length=255)),
                ('same_college', models.BooleanField(default=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('submitted', 'Submitted'), ('auto_submitted', 'Auto Submitted'), ('disqualified', 'Disqualified')], default='active', max_length=20)),
                ('warnings_used', models.PositiveIntegerField(default=0)),
                ('fullscreen_violations', models.PositiveIntegerField(default=0)),
                ('devtools_violations', models.PositiveIntegerField(default=0)),
                ('question_order', djongo.models.fields.JSONField(default=list)),
                ('option_order_map', djongo.models.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quiz_attempts',
            },
        ),
        migrations.CreateModel(
            name='QuizCertificate',
            fields=[
                ('quiz_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('team_code', models.CharField(max_length=50)),
                ('certificate_url', models.URLField()),
                ('cloudinary_public_id', models.CharField(max_length=255)),
                ('sent_to_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quiz_certificates',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('quiz_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('single', 'Single Answer'), ('multiple', 'Multiple Answer')], default='single', max_length=10)),
                ('options', djongo.models.fields.ArrayField(model_container=quiz.models.question.QuizOption)),
                ('explanation_correct', models.TextField(blank=True)),
                ('explanation_wrong', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quiz_questions',
            },
        ),
        migrations.AddIndex(
            model_name='quizcertificate',
            index=models.Index(fields=['quiz_id', 'team_code'], name='quiz_certif_quiz_id_708755_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz_id', 'team_code'], name='quiz_attemp_quiz_id_729615_idx'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizattempt'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizquestion'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['attempt', 'question'], name='quiz_answer_attempt_b8a4a0_idx'),
        ),
    ]
