# Generated by Django 2.2.28 on 2025-12-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20251218_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='event_name',
            field=models.CharField(blank=True, default='', help_text='Event name, e.g. InnovWEB, SensorShowDown, IdeaArena, Error Erase', max_length=255),
        ),
    ]
